name: CI-PROGRES-AWS
on: [push, pull_request]
jobs:
  build:
    name: Docker
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        flag: [ba, bb, bc, bd, be, bf, bg, bh, bi, bj, bk, bl, bm, bn, bo, bp, bq, br, bs, bt]
    steps:
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_mine
      continue-on-error: true
      run: |
          echo "ab"
